name: bae_dualarm_doll_in_box

image_shape: [3, 240, 320]
dataset_path: data/baetae/251010/diffusion_doll_in_box_251010.hdf5

shape_meta: &shape_meta
  obs:
    image0:   # Head camera 242422304502
      shape: [3, 240, 320]
      type: rgb
    image1:   # Front camera 336222070518
      shape: [3, 240, 320]
      type: rgb
    robot_pose_L:
      shape: [3]
      type: low_dim
    robot_quat_L:
      shape: [4]
      type: low_dim
    robot_pose_R:
      shape: [3]
      type: low_dim
    robot_quat_R:
      shape: [4]
      type: low_dim
    hand_pose_L:
      shape: [7]
      type: low_dim
    hand_pose_R:
      shape: [7]
      type: low_dim
    
  action: 
    shape: [32] # robot_pose_L[3] + robot_rot6d_L[6] + robot_pose_R[3] + robot_rot6d_R[6] + hand_pose_L[7] + hand_pose_R[7]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  # pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  # n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  # max_train_episodes: null
  # delta_action: False
  abs_action: True
