name: bae_dualarm_box_image_abs

image_shape: [3, 240, 320]
dataset_path: &dataset_path data/baetae/250912/diffusion_push_box_0912.hdf5

shape_meta: &shape_meta
  obs:
    image0:   # Head camera 242422304502
      shape: [3, 240, 320]
      type: rgb
    image1:   # Front camera 336222070518
     shape: [3, 240, 320]
     type: rgb
    robot_pose_L:
      shape: [3]
      type: low_dim
    robot_quat_L:
      shape: [4]
      type: low_dim
    robot_pose_R:
      shape: [3]
      type: low_dim
    robot_quat_R:
      shape: [4]
      type: low_dim
    # robot_gripper_qpos:
    #   shape: [1]
    #   type: low_dim
  action: 
    shape: [18] # robot0: pose[3] + 6d_rotation[6] / robot1: pose[3] + 6d_rotation[6] 

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: True
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  # val_ratio: 0.02

